import * as theme from 'react-syntax-highlighter/dist/esm/styles/prism';

const styles = {
    "dark": theme.dark,
    "funky": theme.funky,
    "okaidia": theme.okaidia,
    "solarizedlight": theme.solarizedlight,
    "tomorrow": theme.tomorrow,
    "twilight": theme.twilight,
    "prism": theme.prism,
    "a11yDark": theme.a11yDark,
    "atomDark": theme.atomDark,
    "base16AteliersulphurpoolLight": theme.base16AteliersulphurpoolLight,
    "cb": theme.cb,
    "coldarkCold": theme.coldarkCold,
    "coldarkDark": theme.coldarkDark,
    "coyWithoutShadows": theme.coyWithoutShadows,
    "darcula": theme.darcula,
    "dracula": theme.dracula,
    "duotoneDark": theme.duotoneDark,
    "duotoneEarth": theme.duotoneEarth,
    "duotoneForest": theme.duotoneForest,
    "duotoneLight": theme.duotoneLight,
    "duotoneSea": theme.duotoneSea,
    "duotoneSpace": theme.duotoneSpace,
    "ghcolors": theme.ghcolors,
    "gruvboxDark": theme.gruvboxDark,
    "gruvboxLight": theme.gruvboxLight,
    "holiTheme": theme.holiTheme,
    "hopscotch": theme.hopscotch,
    "lucario": theme.lucario,
    "materialDark": theme.materialDark,
    "materialLight": theme.materialLight,
    "materialOceanic": theme.materialOceanic,
    "nightOwl": theme.nightOwl,
    "nord": theme.nord,
    "oneDark": theme.oneDark,
    "oneLight": theme.oneLight,
    "pojoaque": theme.pojoaque,
    "shadesOfPurple": theme.shadesOfPurple,
    "solarizedDarkAtom": theme.solarizedDarkAtom,
    "synthwave84": theme.synthwave84,
    "vs": theme.vs,
    "vscDarkPlus": theme.vscDarkPlus,
    "xonokai": theme.xonokai,
    "zTouch": theme.zTouch
}

export default styles;
